// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoteCalc.Database;

namespace VoteCalc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191109141640_AddValidVoteToVoteEnity")]
    partial class AddValidVoteToVoteEnity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VoteCalc.Database.Entity.CandidateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Party");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("VoteCalc.Database.Entity.VoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CandidateEntityId");

                    b.Property<bool>("ValidVote");

                    b.Property<int?>("VotersEntityId");

                    b.HasKey("Id");

                    b.HasIndex("CandidateEntityId");

                    b.HasIndex("VotersEntityId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("VoteCalc.Database.Entity.VotersEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Pesel");

                    b.HasKey("Id");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("VoteCalc.Database.Entity.VoteEntity", b =>
                {
                    b.HasOne("VoteCalc.Database.Entity.CandidateEntity", "CandidateEntity")
                        .WithMany()
                        .HasForeignKey("CandidateEntityId");

                    b.HasOne("VoteCalc.Database.Entity.VotersEntity", "VotersEntity")
                        .WithMany()
                        .HasForeignKey("VotersEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
